apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-aspnet
  namespace: dotnet-aspnet
  labels:
    app: dotnet-aspnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-aspnet
  template:
    metadata:
      labels:
        app: dotnet-aspnet
    spec:
      containers:
      - name: dotnet-aspnet
        image: dotnet-aspnet
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      restartPolicy: Always
